"""
Cover Letter & Email Page - Job Application Assistant

Display and copy generated cover letter and email content.
"""

import streamlit as st
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from dotenv import load_dotenv
load_dotenv(project_root / ".env")

st.set_page_config(
    page_title="Cover Letter & Email - Job Application Assistant",
    page_icon="✉️",
    layout="wide"
)

st.title("✉️ Cover Letter & Email")
st.markdown("View and copy your generated cover letter and outreach email")

# Check if we have results
if "final_state" not in st.session_state or not st.session_state.final_state:
    st.warning("⚠️ No pipeline results found. Please run the pipeline first.")
    if st.button("🚀 Go to Run Pipeline"):
        st.switch_page("pages/2_🚀_Run_Pipeline.py")
    st.stop()

state = st.session_state.final_state

# Get JD info for context
structured_jd = state.get("structured_jd")

# Helper function
def safe_get(obj, key, default=""):
    if hasattr(obj, key):
        return getattr(obj, key)
    elif isinstance(obj, dict):
        return obj.get(key, default)
    return default

# Display company/role info
if structured_jd:
    company = safe_get(structured_jd, 'company_name', 'Unknown')
    role = safe_get(structured_jd, 'role_title', 'Unknown')
    st.info(f"📌 **Target Position:** {role} at {company}")

st.markdown("---")

# Tabs for Cover Letter and Email
tab1, tab2 = st.tabs(["📝 Cover Letter", "📧 Outreach Email"])

with tab1:
    st.markdown("### 📝 Cover Letter")
    
    cover_letter_text = state.get("cover_letter_text", "")
    cover_letter = state.get("cover_letter")
    
    # Check compliance score
    cl_compliance_score = state.get("cl_compliance_score", 0)
    cl_compliance_passed = state.get("cl_compliance_passed", False)
    
    col1, col2 = st.columns([3, 1])
    with col2:
        if cl_compliance_score > 0:
            st.metric(
                "Compliance Score",
                f"{cl_compliance_score:.0f}%",
                delta="✅ Passed" if cl_compliance_passed else "⚠️ Below target"
            )
    
    if cover_letter_text:
        # Word count
        word_count = len(cover_letter_text.split())
        st.caption(f"📊 Word count: {word_count}")
        
        # Display cover letter
        st.text_area(
            "Cover Letter Content",
            value=cover_letter_text,
            height=400,
            key="cover_letter_display"
        )
        
        # Download buttons
        col1, col2 = st.columns(2)
        with col1:
            st.download_button(
                "⬇️ Download as TXT",
                data=cover_letter_text,
                file_name="cover_letter.txt",
                mime="text/plain",
                use_container_width=True
            )
        with col2:
            # Create formatted version
            formatted_cl = f"""COVER LETTER
{'='*50}

{cover_letter_text}

{'='*50}
Generated by Job Application Assistant
"""
            st.download_button(
                "⬇️ Download Formatted",
                data=formatted_cl,
                file_name="cover_letter_formatted.txt",
                mime="text/plain",
                use_container_width=True
            )
        
        # Cover letter analysis
        with st.expander("📊 Cover Letter Analysis"):
            st.markdown("**Key Elements Check:**")
            
            # Check for key elements
            checks = {
                "Company Name Mentioned": company.lower() in cover_letter_text.lower() if company and company != "Unknown" else False,
                "Role Title Mentioned": role.lower() in cover_letter_text.lower() if role and role != "Unknown" else False,
                "Has Opening": "dear" in cover_letter_text.lower() or "hiring" in cover_letter_text.lower(),
                "Has Closing": "sincerely" in cover_letter_text.lower() or "regards" in cover_letter_text.lower() or "thank" in cover_letter_text.lower(),
                "Word Count OK": 250 <= word_count <= 400,
            }
            
            for check, passed in checks.items():
                if passed:
                    st.write(f"✅ {check}")
                else:
                    st.write(f"❌ {check}")
            
            # Show cover letter object details if available
            if cover_letter:
                st.markdown("---")
                st.markdown("**Cover Letter Metadata:**")
                if hasattr(cover_letter, 'dict'):
                    st.json(cover_letter.dict())
                elif hasattr(cover_letter, 'model_dump'):
                    st.json(cover_letter.model_dump())
                elif isinstance(cover_letter, dict):
                    st.json(cover_letter)
    else:
        st.warning("⚠️ No cover letter was generated.")
        st.info("""
        Possible reasons:
        - Cover letter generation was disabled in config
        - An error occurred during generation
        - The pipeline didn't complete successfully
        """)

with tab2:
    st.markdown("### 📧 Outreach Email")
    
    email_text = state.get("email_text", "")
    email = state.get("email")
    
    if email_text:
        # Parse email sections
        lines = email_text.strip().split('\n')
        subject_line = ""
        body = email_text
        
        # Try to extract subject
        for line in lines:
            if line.lower().startswith("subject:"):
                subject_line = line.replace("Subject:", "").replace("subject:", "").strip()
                body = email_text.replace(line, "").strip()
                break
        
        if subject_line:
            st.text_input("📌 Subject Line", value=subject_line, key="email_subject")
        
        st.text_area(
            "Email Body",
            value=body,
            height=300,
            key="email_display"
        )
        
        # Word count
        word_count = len(email_text.split())
        st.caption(f"📊 Word count: {word_count}")
        
        # Download buttons
        col1, col2 = st.columns(2)
        with col1:
            st.download_button(
                "⬇️ Download as TXT",
                data=email_text,
                file_name="outreach_email.txt",
                mime="text/plain",
                use_container_width=True
            )
        with col2:
            # Create email with header
            formatted_email = f"""OUTREACH EMAIL
{'='*50}

{email_text}

{'='*50}
Generated by Job Application Assistant
"""
            st.download_button(
                "⬇️ Download Formatted",
                data=formatted_email,
                file_name="outreach_email_formatted.txt",
                mime="text/plain",
                use_container_width=True
            )
        
        # Email tips
        with st.expander("💡 Email Tips"):
            st.markdown("""
            **Before Sending:**
            
            1. **Personalize the subject line** - Add recruiter's name if known
            2. **Research the recruiter** - Find their LinkedIn, recent posts
            3. **Attach your resume** - Always include as PDF
            4. **Follow up** - Send a polite follow-up after 5-7 days
            5. **Track responses** - Use the Excel tracker
            
            **Email Best Practices:**
            - Keep under 200 words
            - Have a clear call-to-action
            - Professional but warm tone
            - Proofread carefully
            """)
        
        # Show email object details if available
        if email:
            with st.expander("📊 Email Metadata"):
                if hasattr(email, 'dict'):
                    st.json(email.dict())
                elif hasattr(email, 'model_dump'):
                    st.json(email.model_dump())
                elif isinstance(email, dict):
                    st.json(email)
    else:
        st.warning("⚠️ No email was generated.")
        st.info("""
        Possible reasons:
        - Email generation was disabled in config
        - An error occurred during generation
        - The pipeline didn't complete cover letter stage
        """)

# Additional resources
st.markdown("---")
st.markdown("### 📚 Additional Resources")

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("""
    **Cover Letter Tips:**
    - Keep it concise (250-400 words)
    - Research the company
    - Mention specific role
    - Show enthusiasm
    - Include a clear ask
    """)

with col2:
    st.markdown("""
    **Email Templates:**
    - Cold outreach: Brief intro + value
    - Follow-up: Reference prior contact
    - Thank you: Post-interview gratitude
    - Networking: Mutual connection
    """)

with col3:
    st.markdown("""
    **Next Steps:**
    1. Review and personalize
    2. Proofread carefully
    3. Send at optimal times
    4. Track in Excel sheet
    5. Follow up strategically
    """)

# Navigation
st.markdown("---")
col1, col2 = st.columns(2)
with col1:
    if st.button("📄 View Resume", use_container_width=True):
        st.switch_page("pages/3_📄_Resume.py")
with col2:
    if st.button("🚀 Run Another Pipeline", use_container_width=True):
        st.switch_page("pages/2_🚀_Run_Pipeline.py")
